#!/usr/bin/env python

# Create 2 plots for RT requests
# Data are hand collected from RT as requests per month
# the first plot shows ti distribution of RT tickets vs. sw-related tickets
# the second plot show side by side monthly sw requests as a bar graph

import matplotlib.pyplot as plt
import numpy as np
import matplotlib.ticker as ticker
from scipy import interpolate 


# collected from RT tickets, per month/year for all requests and sw requests
all2019 = [125,95,208,175,128,97,148,157,121,148,76,73]
all2020 = [138,118,125,160,116,103,105,117,113,108,135,112]
all2021 = [228,163,136,157,86]
sw2019  = [18,17,20,20,23,25,29,35,27,30,10,11] 
sw2020  = [19,23,11,25,18,16,11,15,23,11,23,20] 
sw2021  = [28,22,21,16,7]   

# set generic plot params
params = {"axes.titleweight":"bold", 
          "figure.facecolor": (1.0, 1.0, 1.0, 1.0),
          "axes.facecolor":(1.0, 1.0, 1.0, 1.0),
          "axes.titlepad": 18,              # vertical space for plot title
          'axes.titlecolor':'blue',         # title color
          'axes.titleweight': 'bold',       # title weight
          'axes.titlesize': 'large',        # title size
          "axes.labelcolor":'blue',         # x,y-axes titles color
          "axes.labelsize" : "12",          # x,y-axes size
		  'figure.subplot.bottom': 0.18,    # space below x-axis title
}

plt.rcParams.update(params)

def printAllRequests():
    plt.figure(1)
    # output file name
    name = "allRequests"

    # points and labels for x-axis
    total_m = len(sw2019) + len(sw2020) + len(sw2021) + 1
    x = np.array(range(1,total_m)) #  months for 2019-2020-2021 (not full)
    xlabels = ['2019-01','201902','2019-03','2019-04','2019-05','2019-06',
               '2019-07','2019-08','2019-09','2019-10','2019-11','2019-12',
               '2020-01','2020-02','2020-03','2020-04','2020-05','2020-06',
		       '2020-07','2020-08','2020-09','2020-10','2020-11','2020-12',
               '2021-01','2021-02','2021-03','2021-04','2021-05'
		      ]
    # data points 
    y1 = sw2019 + sw2020 + sw2021       # sw requests per month
    y2 = all2019 + all2020 + all2021    # all requests per month

    # smooth data over 300 points, this replaces 
    # obsolete python2 scipy.interpolate.spline
    x_smooth = np.linspace(x.min(), x.max(), 300)
    f1 = interpolate.interp1d(x, y1,kind="quadratic")
    f2 = interpolate.interp1d(x, y2,kind="quadratic")
    y1_smooth = f1(x_smooth)
    y2_smooth = f2(x_smooth)

    # set symbols and lines 
    c1 = 'crimson'
    c2 = 'blue'  
    alpha = 0.4    # alpha
    marker = 'o'   # marker type circle
    msize = 5      # marker size

    # plot data for all tickets 
    plt.plot(x_smooth,y2_smooth, label='all tickets', color=c2)
    plt.plot(x, y2, marker, markersize=msize, color=c2, alpha=alpha)

    # plot data for sw tickets 
    plt.plot(x_smooth,y1_smooth, label='software tickets', color=c1)
    plt.plot(x, y1, marker, markersize=msize, color=c1, alpha=alpha)

    # set plot properties
    plt.title("RT tickets")
    plt.xlabel("Time")
    plt.ylabel("Number of requests")
    plt.xticks(x-1, xlabels, rotation=15, fontsize=9)
    yticks = range(1,int(max(y2)/10+5))
    yticks = np.asarray(yticks) * 10
    plt.yticks(yticks)
    plt.grid(True)
    plt.xlim(x[0]-0.25, x[-1]+0.25)
    plt.ylim(0, (max(y2)/10+1)*10)
    ytick_spacing = 20
    plt.gca().yaxis.set_major_locator(ticker.MultipleLocator(ytick_spacing))
    plt.gca().yaxis.set_minor_locator(ticker.MultipleLocator(5))

    # make every n-th label visible on xaxis
    nvis = 4
    visible_labels = [lab for lab in plt.gca().get_xticklabels() if lab.get_visible() is True and lab.get_text() != '']
    for i in range(len(x)):
        if x[i] % nvis : plt.setp(visible_labels[i], visible=False)
    plt.legend(loc="best") # plot legend
    
        
    # show and save#plt.show()
    plt.savefig("%s.png" % name)
    plt.close(1)

    # handle in params or plt.subplots_adjust(bottom=0.18)  # gives space below xaxis title
    #print (plt.rcParams.keys()) # how to get all params names

def printSwRequests():
    plt.figure(2)
    
    name = "swRequests"
    # collected from RT tickets, per month/year
    y1 = sw2019
    y2 = sw2020
    y3 = sw2021
    
    # points and labels for x-axis
    x = np.array(range(1,13)) #  months 1:12
    xlabels = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
    
    # bars colors by year
    c1 = 'darkviolet'     # 2019
    c2 = 'deepskyblue'    # 2020
    c3 = 'crimson'        # 2021
    
    # plot data
    fig, ax = plt.subplots()
    
    width = 0.25 # bar width
    b1 = plt.bar(x, y1, width, color=c1, label="2019")
    b2 = plt.bar(x+width, y2, width, color=c2,  label="2020")
    b3 = plt.bar(x[0:5]+width*2, y3, width, color=c3,label="2021")
    
    # set plot properties
    plt.xticks(x+width*1.5, xlabels)
    yticks = range(1,int(max(y1+y2+y3)/5+2))
    yticks = np.asarray(yticks) * 5
    plt.yticks(yticks)
    plt.grid(axis='y', alpha=1.0)
    plt.xlim(x[0]-0.5, x[-1]+1)
    plt.title("SW requests")
    plt.xlabel("Time")
    plt.ylabel("Number of requests")
    
    # plot legend
    yl = ["2019 (%d)" % sum(y1), "2020 (%d)" % sum(y2), "2021 (%d)" % sum(y3)]
    plt.legend(yl)
    
    #ax.bar_label(b1, padding=3)
    #ax.bar_label(b2, padding=3)
    #ax.bar_label(b3, padding=3)
    
    # show and save plt.show()
    plt.savefig("%s.png" % name)
    plt.close(2)
    
    #print (plt.rcParams.keys()) # how to get all params names

printAllRequests()
printSwRequests()
