#!/bin/bash

# Purpose: extract lines with "module-hpc"  from /var/log/messages* files
# Arguments: list of files names to process. 
# If empty, assume messages* files in the current directory

if [ $# -eq 0 ];  then
    echo "No arguments supplied. Assuming files in current directory `pwd`"
    files=`ls messages*`
else
    files=$@
fi

prog=`basename $0`

help () {

    printf "\nNAME\n       $prog - eXtract MODule Lines from log files\n"
    printf "SYNOPSIS\n       $prog [OPTION]... [FILE]...\n"
    printf "DESCRIPTION\n"
    printf "       Extract lines with 'module-hpc' from the /var/log/messages-DATE files.\n"
    printf "       For each processed messages-DATE file generate an output file modules-DATE.\n"
    printf "       If no  arguments are given on the command line assume messages-DATE files\n"
    printf "       in the  current directory.\n\n"
    printf "       -h, --h, -help, --help, help\n"
    printf "              print usage info\n\n"

    exit 0
}

case "$1" in
  -*h*|*help)
	help
	;;
  *)
        ;;
esac

for File in $files; do
    if [ ! -f $File ]; then
        echo "Skip $File: not a file"
        continue
    fi
    if [[ $File =~ ".gz" ]];  then
        gunzip $File
        raw=${File%.gz}
        Compress=True
    else
        raw=$File
    fi
    modfile=${raw//messages/modules}
    grep module-hpc $raw > $modfile
    echo  "Wrote " $modfile
    if [ $Compress ]; then
        gzip $raw
        compress=False
    fi
done
